// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package modelgen

type InputTodo struct {
	Text   string `json:"text"`
	UserID int    `json:"userId"`
}

type TodoFilter struct {
	Text   *string `json:"text"`
	Done   *bool   `json:"done"`
	UserID *int    `json:"userId"`
}
